CREATE TABLE pui_widget_type (
	id SERIAL,
	name CHARACTER VARYING(100) NOT NULL,
	type CHARACTER VARYING(100) NOT NULL,
	component CHARACTER VARYING(100) NOT NULL,
	definition TEXT,
	CONSTRAINT PK_PUI_WIDGET_TYPE PRIMARY KEY (ID)
);

CREATE TABLE pui_widget (
	id SERIAL,
	name CHARACTER VARYING(100) NOT NULL,
	typeid INTEGER NOT NULL,
	definition TEXT,
	CONSTRAINT PK_PUI_WIDGET PRIMARY KEY (ID),
	CONSTRAINT FK_PUI_WIDGET_TYPE FOREIGN KEY (TYPEID) REFERENCES PUI_WIDGET_TYPE (ID)
);

CREATE TABLE pui_dashboard (
	id SERIAL,
	name CHARACTER VARYING(100) NOT NULL,
	definition TEXT,
	CONSTRAINT PK_PUI_DASHBOARD PRIMARY KEY (ID)
);
