CREATE TABLE pui_widget_type (
	id INTEGER IDENTITY(1, 1),
	name VARCHAR(100) NOT NULL,
	type VARCHAR(100) NOT NULL,
	component VARCHAR(100) NOT NULL,
	definition VARCHAR(MAX),
	CONSTRAINT PK_PUI_WIDGET_TYPE PRIMARY KEY (ID)
);

CREATE TABLE pui_widget (
	id INTEGER IDENTITY(1, 1),
	name VARCHAR(100) NOT NULL,
	typeid INTEGER NOT NULL,
	definition VARCHAR(MAX),
	CONSTRAINT PK_PUI_WIDGET PRIMARY KEY (ID),
	CONSTRAINT FK_PUI_WIDGET_TYPE FOREIGN KEY (TYPEID) REFERENCES PUI_WIDGET_TYPE (ID)
);

CREATE TABLE pui_dashboard (
	id INTEGER IDENTITY(1, 1),
	name VARCHAR(100) NOT NULL,
	definition VARCHAR(MAX),
	CONSTRAINT PK_PUI_DASHBOARD PRIMARY KEY (ID)
);
